SHOW DATABASES;

CREATE USER 'test1'@'%' IDENTIFIED BY '1234';
CREATE USER 'test1'@'localhost' IDENTIFIED BY '1234';

CREATE DATABASE test1;

GRANT ALL PRIVILEGES ON test1.* TO 'test1'@'%';

SHOW GRANTS FOR 'test1'@'%';